FROM nginx:alpine

# Copy the nginx.conf file to the /etc/nginx directory
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy the index.html file to the /var/www/html directory
COPY ./index.html /var/www/html/index.html
